-- ============================================================
--    suppression des donnees
-- ============================================================

delete from RESERVATION ;
delete from SEANCE ;
delete from PLACE ;
delete from TARIF ;
delete from CATEGORIE_SEANCE ;
delete from CATEGORIE_PLACE ;
delete from ROLE ;
delete from ACTEUR ;
delete from FILM ;
delete from REALISATEUR ;

commit ;

-- ============================================================
--    creation des donnees
-- ============================================================

-- REALISATEUR

insert into REALISATEUR values (  1 , 'SAUTET'     , 'CLAUDE'       , 'FRANCAISE'  ) ;
insert into REALISATEUR values (  2 , 'PINOTEAU'   , 'CLAUDE'       , 'FRANCAISE'  ) ;
insert into REALISATEUR values (  3 , 'DAVOY'      , 'ERIC'         , 'BELGE'      ) ;
insert into REALISATEUR values (  4 , 'ZIDI'       , 'CLAUDE'       , 'FRANCAISE'  ) ;
insert into REALISATEUR values (  5 , 'AUTAN-LARA' , 'CLAUDE'       , 'FRANCAISE'  ) ;
insert into REALISATEUR values (  6 , 'ROHMER'     , 'ERIC'         , 'FRANCAISE'  ) ;
insert into REALISATEUR values (  7 , 'MALLE'      , 'LOUIS'        , 'FRANCAISE'  ) ;
insert into REALISATEUR values (  8 , 'BESSON'     , 'LUC'          , 'FRANCAISE'  ) ;
insert into REALISATEUR values (  9 , 'PREMINGER'  , 'OTTO'         , 'FRANCAISE'  ) ;
insert into REALISATEUR values ( 10 , 'BEINEIX'    , 'JEAN-JACQUES' , 'FRANCAISE'  ) ;
insert into REALISATEUR values ( 11 , 'GERONIMI'   , 'C.'           , 'AMERICAINE' ) ;
insert into REALISATEUR values ( 12 , 'LYNE'       , 'ADRIAN'       , 'AMERICAINE' ) ;
insert into REALISATEUR values ( 13 , 'TRUFFAUT'   , 'FRANCOIS'     , 'FRANCAISE'  ) ;
insert into REALISATEUR values ( 14 , 'COCTEAU'    , 'JEAN'         , 'FRANCAISE'  ) ;
insert into REALISATEUR values ( 24 , 'CACOYANNIS' , 'MICHAEL'      , 'GREC'       ) ;

commit ;

-- FILM

insert into FILM values (  1 , 'GARCON'                       , '01-JAN-83' , 110 , 'COMEDIE'            ,  1 ) ;
insert into FILM values (  2 , 'CESAR ET ROSALIE'             , '02-APR-71' ,  90 , 'COMEDIE'            ,  1 ) ;
insert into FILM values (  3 , 'LA FAC'                       , '24-FEB-89' , 420 , 'SATYRIQUE'          ,  3 ) ;
insert into FILM values (  4 , 'LA PISCINE'                   , '13-MAY-67' , 120 , 'COMEDIE DRAMATIQUE' ,  2 ) ;
insert into FILM values (  5 , 'LA 7EME CIBLE'                , '01-JAN-84' , 115 , 'SUSPENSE'           ,  2 ) ;
insert into FILM values (  6 , 'ASSOCIATION DE MALFAITEURS'   , '01-JAN-87' , 115 , 'COMEDIE'            ,  4 ) ;
insert into FILM values (  7 , 'LA JUMENT VERTE'              , '01-JAN-59' ,  95 , 'COMEDIE'            ,  5 ) ;
insert into FILM values (  8 , 'AU REVOIR LES ENFANTS'        , '01-JAN-87' , 115 , 'DRAME'              ,  7 ) ;
insert into FILM values (  9 , 'LE GRAND SCOGRIFFE'           , '01-JAN-76' , 110 , 'COMEDIE'            ,  2 ) ;
insert into FILM values ( 10 , 'LA FEMME DE L''AVIATEUR'      , '01-JAN-79' , 100 , 'COMEDIE DRAMATIQUE' ,  6 ) ;
insert into FILM values ( 11 , 'L''ANIMAL'                    , '01-JAN-77' , 100 , 'COMEDIE'            ,  4 ) ;
insert into FILM values ( 12 , '9 SEMAINE 1/2'                , '01-JAN-86' , 125 , 'DRAME EROTIQUE'     , 12 ) ;
insert into FILM values ( 13 , 'LA SIRENE DU MISSIPI'         , '01-JAN-69' , 120 , 'COMEDIE POLICIERE'  , 13 ) ;
insert into FILM values ( 14 , 'LA TRAVERSEE DE PARIS'        , '01-JAN-56' ,  95 , 'COMEDIE DRAMATIQUE' ,  5 ) ;
insert into FILM values ( 15 , 'PAULINE A LA PLAGE'           , '01-JAN-82' ,  95 , 'COMEDIE DE MOEURS'  ,  6 ) ;
insert into FILM values ( 16 , 'LE GRAND BLEU'                , '01-JAN-87' , 175 , 'COMEDIE DRAMATIQUE' ,  8 ) ;
insert into FILM values ( 17 , 'ALICE AU PAYS DES MERVEILLES' , '01-JAN-51' ,  85 , 'DESSIN ANIME'       , 11 ) ;
insert into FILM values ( 18 , 'EXODUS'                       , '01-JAN-60' , 190 , 'DRAME'              ,  9 ) ;
insert into FILM values ( 19 , '37 2 LE MATIN'                , '01-JAN-91' , 178 , 'DRAME'              , 10 ) ;
insert into FILM values ( 20 , 'LE RAYON VERT'                , '01-JAN-86' ,  95 , 'COMEDIE DRAMATIQUE' ,  6 ) ;
insert into FILM values ( 21 , 'ZORBA LE GREC'                , '17-DEC-64' , 142 , 'DRAME'              , 42 ) ;

commit ;

-- ACTEUR

commit ;

insert into ACTEUR values (  1 , 'MONTAND'   , 'YVES'        , 'FRANCAISE'    , '13-OCT-21' ) ;
insert into ACTEUR values (  2 , 'GARCIA'    , 'NICOLE'      , 'FRANCAISE'    , '21-FEB-57' ) ;
insert into ACTEUR values (  3 , 'VILLERET'  , 'JACQUES'     , 'FRANCAISE'    , '06-FEB-51' ) ;
insert into ACTEUR values (  4 , 'DUBOIS'    , 'MARIE'       , 'FRANCAISE'    , '12-FEB-37' ) ;
insert into ACTEUR values (  5 , 'SCHNEIDER' , 'ROMY'        , 'AUTRICHIENNE' , '01-APR-42' ) ;
insert into ACTEUR values (  6 , 'FREY'      , 'SAMY'        , 'FRANCAISE'    , '24-MAY-40' ) ;
insert into ACTEUR values (  7 , 'RICARDO'   , 'BRUNOZZI'    , 'ITALIENNE'    , '08-APR-58' ) ;
insert into ACTEUR values (  8 , 'DUPRILLOT' , 'JOHEL'       , 'TCHEQUE'      , '24-APR-68' ) ;
insert into ACTEUR values (  9 , 'LESTRADOS' , 'DOMINIQUOS'  , 'MEXICAINE'    , '19-FEB-69' ) ;
insert into ACTEUR values ( 10 , 'DELON'     , 'ALAIN'       , 'FRANCAISE'    , '04-OCT-33' ) ;
insert into ACTEUR values ( 11 , 'VENTURA'   , 'LINO'        , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 12 , 'MASSARI'   , 'LEA'         , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 13 , 'POIRET'    , 'JEAN'        , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 14 , 'CLUZET'    , 'FRANCOIS'    , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 15 , 'MALAVOY'   , 'CHRISTOPHE'  , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 16 , 'BOURVIL'   , 'BOURVIL'     , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 17 , 'ROBERT'    , 'YVES'        , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 18 , 'MANESSE'   , 'GASPARD'     , 'ALLEMANDE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 19 , 'BELLI'     , 'AGOSTINA'    , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 20 , 'BRASSEUR'  , 'CLAUDE'      , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 21 , 'MARLAUD'   , 'PHILIPPE'    , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 22 , 'BELMONDO'  , 'JEAN-PAUL'   , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 23 , 'ROURKE'    , 'MICKEY'      , 'AMERICAINE'   , '01-JAN-01' ) ;
insert into ACTEUR values ( 24 , 'BASINGER'  , 'KIM'         , 'AMERICAINE'   , '01-JAN-01' ) ;
insert into ACTEUR values ( 25 , 'DENEUVE'   , 'CATHERINE'   , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 26 , 'GABIN'     , 'JEAN'        , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 27 , 'DE FUNES'  , 'LOUIS'       , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 28 , 'LANGLET'   , 'AMANDA'      , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 29 , 'BARR'      , 'JEAN-MARC'   , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 30 , 'ARQUETTE'  , 'ROSANNA'     , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 31 , 'RENO'      , 'JEAN'        , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 32 , 'NEWMAN'    , 'PAUL'        , 'AMERICAINE'   , '01-JAN-01' ) ;
insert into ACTEUR values ( 33 , 'DALLE'     , 'BEATRICE'    , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 34 , 'ANGLADE'   , 'JEAN-HUGUES' , 'FRANCAISE'    , '01-JAN-01' ) ;
insert into ACTEUR values ( 35 , 'RIVIERE'   , 'MARIE'       , 'FRANCAISE'    , '01-JAN-01' ) ;

commit ;

-- ROLE

insert into ROLE values (  1 ,  1 , 'ALEX'                         ) ;
insert into ROLE values (  2 ,  1 , 'CLAIRE'                       ) ;
insert into ROLE values (  3 ,  1 , 'GILBERT'                      ) ;
insert into ROLE values (  4 ,  1 , 'MARIE PIERRE'                 ) ;
insert into ROLE values (  1 ,  2 , 'CESAR'                        ) ;
insert into ROLE values (  5 ,  2 , 'ROSALIE'                      ) ;
insert into ROLE values (  6 ,  2 , 'DAVID'                        ) ;
insert into ROLE values (  5 ,  4 , 'MARIE'                        ) ;
insert into ROLE values ( 10 ,  4 , 'MAURICE'                      ) ;
insert into ROLE values (  7 ,  4 , 'LARNAQUE'                     ) ;
insert into ROLE values (  7 ,  3 , 'NANARD'                       ) ;
insert into ROLE values (  8 ,  3 , 'BAUDERON'                     ) ;
insert into ROLE values (  9 ,  3 , 'COUKY'                        ) ;
insert into ROLE values ( 11 ,  5 , 'BASTIEN'                      ) ;
insert into ROLE values ( 12 ,  5 , 'NELLY'                        ) ;
insert into ROLE values ( 13 ,  5 , 'JEAN'                         ) ;
insert into ROLE values ( 14 ,  6 , 'THIERRY'                      ) ;
insert into ROLE values ( 15 ,  6 , 'GERARD'                       ) ;
insert into ROLE values ( 16 ,  7 , 'HONORE HAUDOIN'               ) ;
insert into ROLE values ( 18 ,  8 , 'JUIEN'                        ) ;
insert into ROLE values (  1 ,  9 , 'MORLAND'                      ) ;
insert into ROLE values ( 19 ,  9 , 'AMANDINE'                     ) ;
insert into ROLE values ( 20 ,  9 , 'ARI'                          ) ;
insert into ROLE values ( 21 , 10 , 'FRANCOIS'                     ) ;
insert into ROLE values ( 22 , 11 , 'MICHEL GAUCHER/BRUNO FERRARI' ) ;
insert into ROLE values ( 23 , 12 , 'JOHN'                         ) ;
insert into ROLE values ( 24 , 12 , 'ELISABETH'                    ) ;
insert into ROLE values ( 22 , 13 , 'LOUIS MAHE'                   ) ;
insert into ROLE values ( 25 , 13 , 'JULIE ROUSSEL'                ) ;
insert into ROLE values ( 26 , 14 , 'GRAND-GIL'                    ) ;
insert into ROLE values ( 16 , 14 , 'MARTIN'                       ) ;
insert into ROLE values ( 27 , 14 , 'JAMBIER'                      ) ;
insert into ROLE values ( 28 , 15 , 'PAULINE'                      ) ;
insert into ROLE values ( 29 , 16 , ''                             ) ;
insert into ROLE values ( 30 , 16 , ''                             ) ;
insert into ROLE values ( 31 , 16 , ''                             ) ;
insert into ROLE values ( 32 , 18 , 'ARI BEN CANNAN'               ) ;
insert into ROLE values ( 33 , 19 , 'BETTY'                        ) ;
insert into ROLE values ( 34 , 19 , 'ZORG'                         ) ;
insert into ROLE values ( 35 , 20 , 'DELPHINE'                     ) ;

commit ;

-- CATEGORIE_PLACE

insert into CATEGORIE_PLACE values (  'A' , 'categorie place A'  ) ;
insert into CATEGORIE_PLACE values (  'B' , 'categorie place B'  ) ;
insert into CATEGORIE_PLACE values (  'S' , 'categorie speciale' ) ;

commit ;

-- CATEGORIE_SEANCE

insert into CATEGORIE_SEANCE values ( 'A' , 'categorie seance A' ) ;
insert into CATEGORIE_SEANCE values ( 'B' , 'categorie seance B' ) ;
insert into CATEGORIE_SEANCE values ( 'C' , 'categorie seance C' ) ;

commit ;

-- TARIF

insert into TARIF values ( 'A' , 'A' ,  20) ;
insert into TARIF values ( 'A' , 'B' ,  30) ;
insert into TARIF values ( 'A' , 'C' ,  50) ;
insert into TARIF values ( 'B' , 'A' ,  40) ;
insert into TARIF values ( 'B' , 'B' ,  60) ;
insert into TARIF values ( 'B' , 'C' , 100) ;

commit ;

-- PLACE

insert into PLACE values (   0 , 'A' ) ;
insert into PLACE values (   1 , 'A' ) ;
insert into PLACE values (   2 , 'A' ) ;
insert into PLACE values (   3 , 'A' ) ;
insert into PLACE values (   4 , 'A' ) ;
insert into PLACE values (   5 , 'A' ) ;
insert into PLACE values (   6 , 'A' ) ;
insert into PLACE values (   7 , 'A' ) ;
insert into PLACE values (   8 , 'A' ) ;
insert into PLACE values (   9 , 'A' ) ;
insert into PLACE values (  10 , 'A' ) ;
insert into PLACE values (  11 , 'A' ) ;
insert into PLACE values (  12 , 'A' ) ;
insert into PLACE values (  13 , 'A' ) ;
insert into PLACE values (  14 , 'A' ) ;
insert into PLACE values (  15 , 'A' ) ;
insert into PLACE values (  16 , 'A' ) ;
insert into PLACE values (  17 , 'A' ) ;
insert into PLACE values (  18 , 'A' ) ;
insert into PLACE values (  19 , 'A' ) ;
insert into PLACE values (  20 , 'A' ) ;
insert into PLACE values (  21 , 'A' ) ;
insert into PLACE values (  22 , 'A' ) ;
insert into PLACE values (  23 , 'A' ) ;
insert into PLACE values (  24 , 'A' ) ;
insert into PLACE values (  25 , 'A' ) ;
insert into PLACE values (  26 , 'A' ) ;
insert into PLACE values (  27 , 'A' ) ;
insert into PLACE values (  28 , 'A' ) ;
insert into PLACE values (  29 , 'A' ) ;
insert into PLACE values (  30 , 'A' ) ;
insert into PLACE values (  31 , 'A' ) ;
insert into PLACE values (  32 , 'A' ) ;
insert into PLACE values (  33 , 'A' ) ;
insert into PLACE values (  34 , 'A' ) ;
insert into PLACE values (  35 , 'A' ) ;
insert into PLACE values (  36 , 'A' ) ;
insert into PLACE values (  37 , 'A' ) ;
insert into PLACE values (  38 , 'A' ) ;
insert into PLACE values (  39 , 'A' ) ;
insert into PLACE values (  40 , 'A' ) ;
insert into PLACE values (  41 , 'A' ) ;
insert into PLACE values (  42 , 'A' ) ;
insert into PLACE values (  43 , 'A' ) ;
insert into PLACE values (  44 , 'A' ) ;
insert into PLACE values (  45 , 'A' ) ;
insert into PLACE values (  46 , 'A' ) ;
insert into PLACE values (  47 , 'A' ) ;
insert into PLACE values (  48 , 'A' ) ;
insert into PLACE values (  49 , 'A' ) ;
insert into PLACE values (  50 , 'A' ) ;
insert into PLACE values (  51 , 'A' ) ;
insert into PLACE values (  52 , 'A' ) ;
insert into PLACE values (  53 , 'A' ) ;
insert into PLACE values (  54 , 'A' ) ;
insert into PLACE values (  55 , 'A' ) ;
insert into PLACE values (  56 , 'A' ) ;
insert into PLACE values (  57 , 'A' ) ;
insert into PLACE values (  58 , 'A' ) ;
insert into PLACE values (  59 , 'A' ) ;
insert into PLACE values (  60 , 'A' ) ;
insert into PLACE values (  61 , 'A' ) ;
insert into PLACE values (  62 , 'A' ) ;
insert into PLACE values (  63 , 'A' ) ;
insert into PLACE values (  64 , 'A' ) ;
insert into PLACE values (  65 , 'A' ) ;
insert into PLACE values (  66 , 'A' ) ;
insert into PLACE values (  67 , 'A' ) ;
insert into PLACE values (  68 , 'A' ) ;
insert into PLACE values (  69 , 'A' ) ;
insert into PLACE values (  70 , 'A' ) ;
insert into PLACE values (  71 , 'A' ) ;
insert into PLACE values (  72 , 'A' ) ;
insert into PLACE values (  73 , 'A' ) ;
insert into PLACE values (  74 , 'A' ) ;
insert into PLACE values (  75 , 'A' ) ;
insert into PLACE values (  76 , 'A' ) ;
insert into PLACE values (  77 , 'A' ) ;
insert into PLACE values (  78 , 'A' ) ;
insert into PLACE values (  79 , 'A' ) ;
insert into PLACE values (  80 , 'A' ) ;
insert into PLACE values (  81 , 'A' ) ;
insert into PLACE values (  82 , 'A' ) ;
insert into PLACE values (  83 , 'A' ) ;
insert into PLACE values (  84 , 'A' ) ;
insert into PLACE values (  85 , 'A' ) ;
insert into PLACE values (  86 , 'A' ) ;
insert into PLACE values (  87 , 'A' ) ;
insert into PLACE values (  88 , 'A' ) ;
insert into PLACE values (  89 , 'A' ) ;
insert into PLACE values (  90 , 'A' ) ;
insert into PLACE values (  91 , 'A' ) ;
insert into PLACE values (  92 , 'A' ) ;
insert into PLACE values (  93 , 'A' ) ;
insert into PLACE values (  94 , 'A' ) ;
insert into PLACE values (  95 , 'A' ) ;
insert into PLACE values (  96 , 'A' ) ;
insert into PLACE values (  97 , 'A' ) ;
insert into PLACE values (  98 , 'A' ) ;
insert into PLACE values (  99 , 'A' ) ;
insert into PLACE values ( 100 , 'A' ) ;
insert into PLACE values ( 101 , 'A' ) ;
insert into PLACE values ( 102 , 'A' ) ;
insert into PLACE values ( 103 , 'A' ) ;
insert into PLACE values ( 104 , 'A' ) ;
insert into PLACE values ( 105 , 'A' ) ;
insert into PLACE values ( 106 , 'A' ) ;
insert into PLACE values ( 107 , 'A' ) ;
insert into PLACE values ( 108 , 'A' ) ;
insert into PLACE values ( 109 , 'A' ) ;
insert into PLACE values ( 110 , 'A' ) ;
insert into PLACE values ( 111 , 'A' ) ;
insert into PLACE values ( 112 , 'A' ) ;
insert into PLACE values ( 113 , 'A' ) ;
insert into PLACE values ( 114 , 'A' ) ;
insert into PLACE values ( 115 , 'A' ) ;
insert into PLACE values ( 116 , 'A' ) ;
insert into PLACE values ( 117 , 'A' ) ;
insert into PLACE values ( 118 , 'A' ) ;
insert into PLACE values ( 119 , 'A' ) ;
insert into PLACE values ( 120 , 'A' ) ;
insert into PLACE values ( 121 , 'A' ) ;
insert into PLACE values ( 122 , 'A' ) ;
insert into PLACE values ( 123 , 'A' ) ;
insert into PLACE values ( 124 , 'A' ) ;
insert into PLACE values ( 125 , 'A' ) ;
insert into PLACE values ( 126 , 'A' ) ;
insert into PLACE values ( 127 , 'A' ) ;
insert into PLACE values ( 128 , 'A' ) ;
insert into PLACE values ( 129 , 'A' ) ;
insert into PLACE values ( 130 , 'A' ) ;
insert into PLACE values ( 131 , 'A' ) ;
insert into PLACE values ( 132 , 'A' ) ;
insert into PLACE values ( 133 , 'A' ) ;
insert into PLACE values ( 134 , 'A' ) ;
insert into PLACE values ( 135 , 'A' ) ;
insert into PLACE values ( 136 , 'A' ) ;
insert into PLACE values ( 137 , 'A' ) ;
insert into PLACE values ( 138 , 'A' ) ;
insert into PLACE values ( 139 , 'A' ) ;
insert into PLACE values ( 140 , 'A' ) ;
insert into PLACE values ( 141 , 'A' ) ;
insert into PLACE values ( 142 , 'A' ) ;
insert into PLACE values ( 143 , 'A' ) ;
insert into PLACE values ( 144 , 'A' ) ;
insert into PLACE values ( 145 , 'A' ) ;
insert into PLACE values ( 146 , 'A' ) ;
insert into PLACE values ( 147 , 'A' ) ;
insert into PLACE values ( 148 , 'A' ) ;
insert into PLACE values ( 149 , 'A' ) ;
insert into PLACE values ( 150 , 'A' ) ;
insert into PLACE values ( 151 , 'A' ) ;
insert into PLACE values ( 152 , 'A' ) ;
insert into PLACE values ( 153 , 'A' ) ;
insert into PLACE values ( 154 , 'A' ) ;
insert into PLACE values ( 155 , 'A' ) ;
insert into PLACE values ( 156 , 'A' ) ;
insert into PLACE values ( 157 , 'A' ) ;
insert into PLACE values ( 158 , 'A' ) ;
insert into PLACE values ( 159 , 'A' ) ;
insert into PLACE values ( 160 , 'A' ) ;
insert into PLACE values ( 161 , 'A' ) ;
insert into PLACE values ( 162 , 'A' ) ;
insert into PLACE values ( 163 , 'A' ) ;
insert into PLACE values ( 164 , 'A' ) ;
insert into PLACE values ( 165 , 'A' ) ;
insert into PLACE values ( 166 , 'A' ) ;
insert into PLACE values ( 167 , 'A' ) ;
insert into PLACE values ( 168 , 'A' ) ;
insert into PLACE values ( 169 , 'A' ) ;
insert into PLACE values ( 170 , 'A' ) ;
insert into PLACE values ( 171 , 'A' ) ;
insert into PLACE values ( 172 , 'A' ) ;
insert into PLACE values ( 173 , 'A' ) ;
insert into PLACE values ( 174 , 'A' ) ;
insert into PLACE values ( 175 , 'A' ) ;
insert into PLACE values ( 176 , 'A' ) ;
insert into PLACE values ( 177 , 'A' ) ;
insert into PLACE values ( 178 , 'A' ) ;
insert into PLACE values ( 179 , 'A' ) ;
insert into PLACE values ( 180 , 'A' ) ;
insert into PLACE values ( 181 , 'A' ) ;
insert into PLACE values ( 182 , 'A' ) ;
insert into PLACE values ( 183 , 'A' ) ;
insert into PLACE values ( 184 , 'A' ) ;
insert into PLACE values ( 185 , 'A' ) ;
insert into PLACE values ( 186 , 'A' ) ;
insert into PLACE values ( 187 , 'A' ) ;
insert into PLACE values ( 188 , 'A' ) ;
insert into PLACE values ( 189 , 'A' ) ;
insert into PLACE values ( 190 , 'A' ) ;
insert into PLACE values ( 191 , 'A' ) ;
insert into PLACE values ( 192 , 'A' ) ;
insert into PLACE values ( 193 , 'A' ) ;
insert into PLACE values ( 194 , 'A' ) ;
insert into PLACE values ( 195 , 'A' ) ;
insert into PLACE values ( 196 , 'A' ) ;
insert into PLACE values ( 197 , 'A' ) ;
insert into PLACE values ( 198 , 'A' ) ;
insert into PLACE values ( 199 , 'A' ) ;
insert into PLACE values ( 200 , 'A' ) ;
insert into PLACE values ( 201 , 'A' ) ;
insert into PLACE values ( 202 , 'A' ) ;
insert into PLACE values ( 203 , 'A' ) ;
insert into PLACE values ( 204 , 'A' ) ;
insert into PLACE values ( 205 , 'A' ) ;
insert into PLACE values ( 206 , 'A' ) ;
insert into PLACE values ( 207 , 'A' ) ;
insert into PLACE values ( 208 , 'A' ) ;
insert into PLACE values ( 209 , 'A' ) ;
insert into PLACE values ( 210 , 'A' ) ;
insert into PLACE values ( 211 , 'A' ) ;
insert into PLACE values ( 212 , 'A' ) ;
insert into PLACE values ( 213 , 'A' ) ;
insert into PLACE values ( 214 , 'A' ) ;
insert into PLACE values ( 215 , 'A' ) ;
insert into PLACE values ( 216 , 'A' ) ;
insert into PLACE values ( 217 , 'A' ) ;
insert into PLACE values ( 218 , 'A' ) ;
insert into PLACE values ( 219 , 'A' ) ;
insert into PLACE values ( 220 , 'A' ) ;
insert into PLACE values ( 221 , 'A' ) ;
insert into PLACE values ( 222 , 'A' ) ;
insert into PLACE values ( 223 , 'A' ) ;
insert into PLACE values ( 224 , 'A' ) ;
insert into PLACE values ( 225 , 'A' ) ;
insert into PLACE values ( 226 , 'A' ) ;
insert into PLACE values ( 227 , 'A' ) ;
insert into PLACE values ( 228 , 'A' ) ;
insert into PLACE values ( 229 , 'A' ) ;
insert into PLACE values ( 230 , 'A' ) ;
insert into PLACE values ( 231 , 'A' ) ;
insert into PLACE values ( 232 , 'A' ) ;
insert into PLACE values ( 233 , 'A' ) ;
insert into PLACE values ( 234 , 'A' ) ;
insert into PLACE values ( 235 , 'A' ) ;
insert into PLACE values ( 236 , 'A' ) ;
insert into PLACE values ( 237 , 'A' ) ;
insert into PLACE values ( 238 , 'A' ) ;
insert into PLACE values ( 239 , 'A' ) ;
insert into PLACE values ( 240 , 'A' ) ;
insert into PLACE values ( 241 , 'A' ) ;
insert into PLACE values ( 242 , 'A' ) ;
insert into PLACE values ( 243 , 'A' ) ;
insert into PLACE values ( 244 , 'A' ) ;
insert into PLACE values ( 245 , 'A' ) ;
insert into PLACE values ( 246 , 'A' ) ;
insert into PLACE values ( 247 , 'A' ) ;
insert into PLACE values ( 248 , 'A' ) ;
insert into PLACE values ( 249 , 'A' ) ;
insert into PLACE values ( 250 , 'A' ) ;
insert into PLACE values ( 251 , 'A' ) ;
insert into PLACE values ( 252 , 'A' ) ;
insert into PLACE values ( 253 , 'A' ) ;
insert into PLACE values ( 254 , 'A' ) ;
insert into PLACE values ( 255 , 'A' ) ;
insert into PLACE values ( 256 , 'A' ) ;
insert into PLACE values ( 257 , 'A' ) ;
insert into PLACE values ( 258 , 'A' ) ;
insert into PLACE values ( 259 , 'A' ) ;
insert into PLACE values ( 260 , 'A' ) ;
insert into PLACE values ( 261 , 'A' ) ;
insert into PLACE values ( 262 , 'A' ) ;
insert into PLACE values ( 263 , 'A' ) ;
insert into PLACE values ( 264 , 'A' ) ;
insert into PLACE values ( 265 , 'A' ) ;
insert into PLACE values ( 266 , 'A' ) ;
insert into PLACE values ( 267 , 'A' ) ;
insert into PLACE values ( 268 , 'A' ) ;
insert into PLACE values ( 269 , 'A' ) ;
insert into PLACE values ( 270 , 'A' ) ;
insert into PLACE values ( 271 , 'A' ) ;
insert into PLACE values ( 272 , 'A' ) ;
insert into PLACE values ( 273 , 'A' ) ;
insert into PLACE values ( 274 , 'A' ) ;
insert into PLACE values ( 275 , 'A' ) ;
insert into PLACE values ( 276 , 'A' ) ;
insert into PLACE values ( 277 , 'A' ) ;
insert into PLACE values ( 278 , 'A' ) ;
insert into PLACE values ( 279 , 'A' ) ;
insert into PLACE values ( 280 , 'A' ) ;
insert into PLACE values ( 281 , 'A' ) ;
insert into PLACE values ( 282 , 'A' ) ;
insert into PLACE values ( 283 , 'A' ) ;
insert into PLACE values ( 284 , 'A' ) ;
insert into PLACE values ( 285 , 'A' ) ;
insert into PLACE values ( 286 , 'A' ) ;
insert into PLACE values ( 287 , 'A' ) ;
insert into PLACE values ( 288 , 'A' ) ;
insert into PLACE values ( 289 , 'A' ) ;
insert into PLACE values ( 290 , 'A' ) ;
insert into PLACE values ( 291 , 'A' ) ;
insert into PLACE values ( 292 , 'A' ) ;
insert into PLACE values ( 293 , 'A' ) ;
insert into PLACE values ( 294 , 'A' ) ;
insert into PLACE values ( 295 , 'A' ) ;
insert into PLACE values ( 296 , 'A' ) ;
insert into PLACE values ( 297 , 'A' ) ;
insert into PLACE values ( 298 , 'A' ) ;
insert into PLACE values ( 299 , 'A' ) ;
insert into PLACE values ( 300 , 'A' ) ;
insert into PLACE values ( 301 , 'A' ) ;
insert into PLACE values ( 302 , 'A' ) ;
insert into PLACE values ( 303 , 'A' ) ;
insert into PLACE values ( 304 , 'A' ) ;
insert into PLACE values ( 305 , 'A' ) ;
insert into PLACE values ( 306 , 'A' ) ;
insert into PLACE values ( 307 , 'A' ) ;
insert into PLACE values ( 308 , 'A' ) ;
insert into PLACE values ( 309 , 'A' ) ;
insert into PLACE values ( 310 , 'A' ) ;
insert into PLACE values ( 311 , 'A' ) ;
insert into PLACE values ( 312 , 'A' ) ;
insert into PLACE values ( 313 , 'A' ) ;
insert into PLACE values ( 314 , 'A' ) ;
insert into PLACE values ( 315 , 'A' ) ;
insert into PLACE values ( 316 , 'A' ) ;
insert into PLACE values ( 317 , 'A' ) ;
insert into PLACE values ( 318 , 'A' ) ;
insert into PLACE values ( 319 , 'A' ) ;
insert into PLACE values ( 320 , 'A' ) ;
insert into PLACE values ( 321 , 'A' ) ;
insert into PLACE values ( 322 , 'A' ) ;
insert into PLACE values ( 323 , 'A' ) ;
insert into PLACE values ( 324 , 'A' ) ;
insert into PLACE values ( 325 , 'A' ) ;
insert into PLACE values ( 326 , 'A' ) ;
insert into PLACE values ( 327 , 'A' ) ;
insert into PLACE values ( 328 , 'A' ) ;
insert into PLACE values ( 329 , 'A' ) ;
insert into PLACE values ( 330 , 'A' ) ;
insert into PLACE values ( 331 , 'A' ) ;
insert into PLACE values ( 332 , 'A' ) ;
insert into PLACE values ( 333 , 'A' ) ;
insert into PLACE values ( 334 , 'A' ) ;
insert into PLACE values ( 335 , 'A' ) ;
insert into PLACE values ( 336 , 'A' ) ;
insert into PLACE values ( 337 , 'A' ) ;
insert into PLACE values ( 338 , 'A' ) ;
insert into PLACE values ( 339 , 'A' ) ;
insert into PLACE values ( 340 , 'A' ) ;
insert into PLACE values ( 341 , 'A' ) ;
insert into PLACE values ( 342 , 'A' ) ;
insert into PLACE values ( 343 , 'A' ) ;
insert into PLACE values ( 344 , 'A' ) ;
insert into PLACE values ( 345 , 'A' ) ;
insert into PLACE values ( 346 , 'A' ) ;
insert into PLACE values ( 347 , 'A' ) ;
insert into PLACE values ( 348 , 'A' ) ;
insert into PLACE values ( 349 , 'A' ) ;
insert into PLACE values ( 350 , 'A' ) ;
insert into PLACE values ( 351 , 'A' ) ;
insert into PLACE values ( 352 , 'A' ) ;
insert into PLACE values ( 353 , 'A' ) ;
insert into PLACE values ( 354 , 'A' ) ;
insert into PLACE values ( 355 , 'A' ) ;
insert into PLACE values ( 356 , 'A' ) ;
insert into PLACE values ( 357 , 'A' ) ;
insert into PLACE values ( 358 , 'A' ) ;
insert into PLACE values ( 359 , 'A' ) ;
insert into PLACE values ( 360 , 'A' ) ;
insert into PLACE values ( 361 , 'A' ) ;
insert into PLACE values ( 362 , 'A' ) ;
insert into PLACE values ( 363 , 'A' ) ;
insert into PLACE values ( 364 , 'A' ) ;
insert into PLACE values ( 365 , 'A' ) ;
insert into PLACE values ( 366 , 'A' ) ;
insert into PLACE values ( 367 , 'A' ) ;
insert into PLACE values ( 368 , 'A' ) ;
insert into PLACE values ( 369 , 'A' ) ;
insert into PLACE values ( 370 , 'A' ) ;
insert into PLACE values ( 371 , 'A' ) ;
insert into PLACE values ( 372 , 'A' ) ;
insert into PLACE values ( 373 , 'A' ) ;
insert into PLACE values ( 374 , 'A' ) ;
insert into PLACE values ( 375 , 'A' ) ;
insert into PLACE values ( 376 , 'A' ) ;
insert into PLACE values ( 377 , 'A' ) ;
insert into PLACE values ( 378 , 'A' ) ;
insert into PLACE values ( 379 , 'A' ) ;
insert into PLACE values ( 380 , 'A' ) ;
insert into PLACE values ( 381 , 'A' ) ;
insert into PLACE values ( 382 , 'A' ) ;
insert into PLACE values ( 383 , 'A' ) ;
insert into PLACE values ( 384 , 'A' ) ;
insert into PLACE values ( 385 , 'A' ) ;
insert into PLACE values ( 386 , 'A' ) ;
insert into PLACE values ( 387 , 'A' ) ;
insert into PLACE values ( 388 , 'A' ) ;
insert into PLACE values ( 389 , 'A' ) ;
insert into PLACE values ( 390 , 'A' ) ;
insert into PLACE values ( 391 , 'A' ) ;
insert into PLACE values ( 392 , 'A' ) ;
insert into PLACE values ( 393 , 'A' ) ;
insert into PLACE values ( 394 , 'A' ) ;
insert into PLACE values ( 395 , 'A' ) ;
insert into PLACE values ( 396 , 'A' ) ;
insert into PLACE values ( 397 , 'A' ) ;
insert into PLACE values ( 398 , 'A' ) ;
insert into PLACE values ( 399 , 'A' ) ;
insert into PLACE values ( 400 , 'A' ) ;
insert into PLACE values ( 401 , 'A' ) ;
insert into PLACE values ( 402 , 'A' ) ;
insert into PLACE values ( 403 , 'A' ) ;
insert into PLACE values ( 404 , 'A' ) ;
insert into PLACE values ( 405 , 'A' ) ;
insert into PLACE values ( 406 , 'A' ) ;
insert into PLACE values ( 407 , 'A' ) ;
insert into PLACE values ( 408 , 'A' ) ;
insert into PLACE values ( 409 , 'A' ) ;
insert into PLACE values ( 410 , 'A' ) ;
insert into PLACE values ( 411 , 'A' ) ;
insert into PLACE values ( 412 , 'A' ) ;
insert into PLACE values ( 413 , 'A' ) ;
insert into PLACE values ( 414 , 'A' ) ;
insert into PLACE values ( 415 , 'A' ) ;
insert into PLACE values ( 416 , 'A' ) ;
insert into PLACE values ( 417 , 'A' ) ;
insert into PLACE values ( 418 , 'A' ) ;
insert into PLACE values ( 419 , 'A' ) ;
insert into PLACE values ( 420 , 'A' ) ;
insert into PLACE values ( 421 , 'A' ) ;
insert into PLACE values ( 422 , 'A' ) ;
insert into PLACE values ( 423 , 'A' ) ;
insert into PLACE values ( 424 , 'A' ) ;
insert into PLACE values ( 425 , 'A' ) ;
insert into PLACE values ( 426 , 'A' ) ;
insert into PLACE values ( 427 , 'A' ) ;
insert into PLACE values ( 428 , 'A' ) ;
insert into PLACE values ( 429 , 'A' ) ;
insert into PLACE values ( 430 , 'A' ) ;
insert into PLACE values ( 431 , 'A' ) ;
insert into PLACE values ( 432 , 'A' ) ;
insert into PLACE values ( 433 , 'A' ) ;
insert into PLACE values ( 434 , 'A' ) ;
insert into PLACE values ( 435 , 'A' ) ;
insert into PLACE values ( 436 , 'A' ) ;
insert into PLACE values ( 437 , 'A' ) ;
insert into PLACE values ( 438 , 'A' ) ;
insert into PLACE values ( 439 , 'A' ) ;
insert into PLACE values ( 440 , 'A' ) ;
insert into PLACE values ( 441 , 'A' ) ;
insert into PLACE values ( 442 , 'A' ) ;
insert into PLACE values ( 443 , 'A' ) ;
insert into PLACE values ( 444 , 'A' ) ;
insert into PLACE values ( 445 , 'A' ) ;
insert into PLACE values ( 446 , 'A' ) ;
insert into PLACE values ( 447 , 'A' ) ;
insert into PLACE values ( 448 , 'A' ) ;
insert into PLACE values ( 449 , 'A' ) ;
insert into PLACE values ( 450 , 'A' ) ;
insert into PLACE values ( 451 , 'A' ) ;
insert into PLACE values ( 452 , 'A' ) ;
insert into PLACE values ( 453 , 'A' ) ;
insert into PLACE values ( 454 , 'A' ) ;
insert into PLACE values ( 455 , 'A' ) ;
insert into PLACE values ( 456 , 'A' ) ;
insert into PLACE values ( 457 , 'A' ) ;
insert into PLACE values ( 458 , 'A' ) ;
insert into PLACE values ( 459 , 'A' ) ;
insert into PLACE values ( 460 , 'A' ) ;
insert into PLACE values ( 461 , 'A' ) ;
insert into PLACE values ( 462 , 'A' ) ;
insert into PLACE values ( 463 , 'A' ) ;
insert into PLACE values ( 464 , 'A' ) ;
insert into PLACE values ( 465 , 'A' ) ;
insert into PLACE values ( 466 , 'A' ) ;
insert into PLACE values ( 467 , 'A' ) ;
insert into PLACE values ( 468 , 'A' ) ;
insert into PLACE values ( 469 , 'A' ) ;
insert into PLACE values ( 470 , 'A' ) ;
insert into PLACE values ( 471 , 'A' ) ;
insert into PLACE values ( 472 , 'A' ) ;
insert into PLACE values ( 473 , 'A' ) ;
insert into PLACE values ( 474 , 'A' ) ;
insert into PLACE values ( 475 , 'A' ) ;
insert into PLACE values ( 476 , 'A' ) ;
insert into PLACE values ( 477 , 'A' ) ;
insert into PLACE values ( 478 , 'A' ) ;
insert into PLACE values ( 479 , 'A' ) ;
insert into PLACE values ( 480 , 'A' ) ;
insert into PLACE values ( 481 , 'A' ) ;
insert into PLACE values ( 482 , 'A' ) ;
insert into PLACE values ( 483 , 'A' ) ;
insert into PLACE values ( 484 , 'A' ) ;
insert into PLACE values ( 485 , 'A' ) ;
insert into PLACE values ( 486 , 'A' ) ;
insert into PLACE values ( 487 , 'A' ) ;
insert into PLACE values ( 488 , 'A' ) ;
insert into PLACE values ( 489 , 'A' ) ;
insert into PLACE values ( 490 , 'A' ) ;
insert into PLACE values ( 491 , 'A' ) ;
insert into PLACE values ( 492 , 'A' ) ;
insert into PLACE values ( 493 , 'A' ) ;
insert into PLACE values ( 494 , 'A' ) ;
insert into PLACE values ( 495 , 'A' ) ;
insert into PLACE values ( 496 , 'A' ) ;
insert into PLACE values ( 497 , 'A' ) ;
insert into PLACE values ( 498 , 'A' ) ;
insert into PLACE values ( 499 , 'A' ) ;
insert into PLACE values ( 500 , 'B' ) ;
insert into PLACE values ( 501 , 'B' ) ;
insert into PLACE values ( 502 , 'B' ) ;
insert into PLACE values ( 503 , 'B' ) ;
insert into PLACE values ( 504 , 'B' ) ;
insert into PLACE values ( 505 , 'B' ) ;
insert into PLACE values ( 506 , 'B' ) ;
insert into PLACE values ( 507 , 'B' ) ;
insert into PLACE values ( 508 , 'B' ) ;
insert into PLACE values ( 509 , 'B' ) ;
insert into PLACE values ( 510 , 'B' ) ;
insert into PLACE values ( 511 , 'B' ) ;
insert into PLACE values ( 512 , 'B' ) ;
insert into PLACE values ( 513 , 'B' ) ;
insert into PLACE values ( 514 , 'B' ) ;
insert into PLACE values ( 515 , 'B' ) ;
insert into PLACE values ( 516 , 'B' ) ;
insert into PLACE values ( 517 , 'B' ) ;
insert into PLACE values ( 518 , 'B' ) ;
insert into PLACE values ( 519 , 'B' ) ;
insert into PLACE values ( 520 , 'B' ) ;
insert into PLACE values ( 521 , 'B' ) ;
insert into PLACE values ( 522 , 'B' ) ;
insert into PLACE values ( 523 , 'B' ) ;
insert into PLACE values ( 524 , 'B' ) ;
insert into PLACE values ( 525 , 'B' ) ;
insert into PLACE values ( 526 , 'B' ) ;
insert into PLACE values ( 527 , 'B' ) ;
insert into PLACE values ( 528 , 'B' ) ;
insert into PLACE values ( 529 , 'B' ) ;
insert into PLACE values ( 530 , 'B' ) ;
insert into PLACE values ( 531 , 'B' ) ;
insert into PLACE values ( 532 , 'B' ) ;
insert into PLACE values ( 533 , 'B' ) ;
insert into PLACE values ( 534 , 'B' ) ;
insert into PLACE values ( 535 , 'B' ) ;
insert into PLACE values ( 536 , 'B' ) ;
insert into PLACE values ( 537 , 'B' ) ;
insert into PLACE values ( 538 , 'B' ) ;
insert into PLACE values ( 539 , 'B' ) ;
insert into PLACE values ( 540 , 'B' ) ;
insert into PLACE values ( 541 , 'B' ) ;
insert into PLACE values ( 542 , 'B' ) ;
insert into PLACE values ( 543 , 'B' ) ;
insert into PLACE values ( 544 , 'B' ) ;
insert into PLACE values ( 545 , 'B' ) ;
insert into PLACE values ( 546 , 'B' ) ;
insert into PLACE values ( 547 , 'B' ) ;
insert into PLACE values ( 548 , 'B' ) ;
insert into PLACE values ( 549 , 'B' ) ;
insert into PLACE values ( 550 , 'B' ) ;
insert into PLACE values ( 551 , 'B' ) ;
insert into PLACE values ( 552 , 'B' ) ;
insert into PLACE values ( 553 , 'B' ) ;
insert into PLACE values ( 554 , 'B' ) ;
insert into PLACE values ( 555 , 'B' ) ;
insert into PLACE values ( 556 , 'B' ) ;
insert into PLACE values ( 557 , 'B' ) ;
insert into PLACE values ( 558 , 'B' ) ;
insert into PLACE values ( 559 , 'B' ) ;
insert into PLACE values ( 560 , 'B' ) ;
insert into PLACE values ( 561 , 'B' ) ;
insert into PLACE values ( 562 , 'B' ) ;
insert into PLACE values ( 563 , 'B' ) ;
insert into PLACE values ( 564 , 'B' ) ;
insert into PLACE values ( 565 , 'B' ) ;
insert into PLACE values ( 566 , 'B' ) ;
insert into PLACE values ( 567 , 'B' ) ;
insert into PLACE values ( 568 , 'B' ) ;
insert into PLACE values ( 569 , 'B' ) ;
insert into PLACE values ( 570 , 'B' ) ;
insert into PLACE values ( 571 , 'B' ) ;
insert into PLACE values ( 572 , 'B' ) ;
insert into PLACE values ( 573 , 'B' ) ;
insert into PLACE values ( 574 , 'B' ) ;
insert into PLACE values ( 575 , 'B' ) ;
insert into PLACE values ( 576 , 'B' ) ;
insert into PLACE values ( 577 , 'B' ) ;
insert into PLACE values ( 578 , 'B' ) ;
insert into PLACE values ( 579 , 'B' ) ;
insert into PLACE values ( 580 , 'B' ) ;
insert into PLACE values ( 581 , 'B' ) ;
insert into PLACE values ( 582 , 'B' ) ;
insert into PLACE values ( 583 , 'B' ) ;
insert into PLACE values ( 584 , 'B' ) ;
insert into PLACE values ( 585 , 'B' ) ;
insert into PLACE values ( 586 , 'B' ) ;
insert into PLACE values ( 587 , 'B' ) ;
insert into PLACE values ( 588 , 'B' ) ;
insert into PLACE values ( 589 , 'B' ) ;
insert into PLACE values ( 590 , 'B' ) ;
insert into PLACE values ( 591 , 'B' ) ;
insert into PLACE values ( 592 , 'B' ) ;
insert into PLACE values ( 593 , 'B' ) ;
insert into PLACE values ( 594 , 'B' ) ;
insert into PLACE values ( 595 , 'B' ) ;
insert into PLACE values ( 596 , 'B' ) ;
insert into PLACE values ( 597 , 'B' ) ;
insert into PLACE values ( 598 , 'B' ) ;
insert into PLACE values ( 599 , 'B' ) ;
insert into PLACE values ( 600 , 'B' ) ;
insert into PLACE values ( 601 , 'B' ) ;
insert into PLACE values ( 602 , 'B' ) ;
insert into PLACE values ( 603 , 'B' ) ;
insert into PLACE values ( 604 , 'B' ) ;
insert into PLACE values ( 605 , 'B' ) ;
insert into PLACE values ( 606 , 'B' ) ;
insert into PLACE values ( 607 , 'B' ) ;
insert into PLACE values ( 608 , 'B' ) ;
insert into PLACE values ( 609 , 'B' ) ;
insert into PLACE values ( 610 , 'B' ) ;
insert into PLACE values ( 611 , 'B' ) ;
insert into PLACE values ( 612 , 'B' ) ;
insert into PLACE values ( 613 , 'B' ) ;
insert into PLACE values ( 614 , 'B' ) ;
insert into PLACE values ( 615 , 'B' ) ;
insert into PLACE values ( 616 , 'B' ) ;
insert into PLACE values ( 617 , 'B' ) ;
insert into PLACE values ( 618 , 'B' ) ;
insert into PLACE values ( 619 , 'B' ) ;
insert into PLACE values ( 620 , 'B' ) ;
insert into PLACE values ( 621 , 'B' ) ;
insert into PLACE values ( 622 , 'B' ) ;
insert into PLACE values ( 623 , 'B' ) ;
insert into PLACE values ( 624 , 'B' ) ;
insert into PLACE values ( 625 , 'B' ) ;
insert into PLACE values ( 626 , 'B' ) ;
insert into PLACE values ( 627 , 'B' ) ;
insert into PLACE values ( 628 , 'B' ) ;
insert into PLACE values ( 629 , 'B' ) ;
insert into PLACE values ( 630 , 'B' ) ;
insert into PLACE values ( 631 , 'B' ) ;
insert into PLACE values ( 632 , 'B' ) ;
insert into PLACE values ( 633 , 'B' ) ;
insert into PLACE values ( 634 , 'B' ) ;
insert into PLACE values ( 635 , 'B' ) ;
insert into PLACE values ( 636 , 'B' ) ;
insert into PLACE values ( 637 , 'B' ) ;
insert into PLACE values ( 638 , 'B' ) ;
insert into PLACE values ( 639 , 'B' ) ;
insert into PLACE values ( 640 , 'B' ) ;
insert into PLACE values ( 641 , 'B' ) ;
insert into PLACE values ( 642 , 'B' ) ;
insert into PLACE values ( 643 , 'B' ) ;
insert into PLACE values ( 644 , 'B' ) ;
insert into PLACE values ( 645 , 'B' ) ;
insert into PLACE values ( 646 , 'B' ) ;
insert into PLACE values ( 647 , 'B' ) ;
insert into PLACE values ( 648 , 'B' ) ;
insert into PLACE values ( 649 , 'B' ) ;
insert into PLACE values ( 650 , 'B' ) ;
insert into PLACE values ( 651 , 'B' ) ;
insert into PLACE values ( 652 , 'B' ) ;
insert into PLACE values ( 653 , 'B' ) ;
insert into PLACE values ( 654 , 'B' ) ;
insert into PLACE values ( 655 , 'B' ) ;
insert into PLACE values ( 656 , 'B' ) ;
insert into PLACE values ( 657 , 'B' ) ;
insert into PLACE values ( 658 , 'B' ) ;
insert into PLACE values ( 659 , 'B' ) ;
insert into PLACE values ( 660 , 'B' ) ;
insert into PLACE values ( 661 , 'B' ) ;
insert into PLACE values ( 662 , 'B' ) ;
insert into PLACE values ( 663 , 'B' ) ;
insert into PLACE values ( 664 , 'B' ) ;
insert into PLACE values ( 665 , 'B' ) ;
insert into PLACE values ( 666 , 'B' ) ;
insert into PLACE values ( 667 , 'B' ) ;
insert into PLACE values ( 668 , 'B' ) ;
insert into PLACE values ( 669 , 'B' ) ;
insert into PLACE values ( 670 , 'B' ) ;
insert into PLACE values ( 671 , 'B' ) ;
insert into PLACE values ( 672 , 'B' ) ;
insert into PLACE values ( 673 , 'B' ) ;
insert into PLACE values ( 674 , 'B' ) ;
insert into PLACE values ( 675 , 'B' ) ;
insert into PLACE values ( 676 , 'B' ) ;
insert into PLACE values ( 677 , 'B' ) ;
insert into PLACE values ( 678 , 'B' ) ;
insert into PLACE values ( 679 , 'B' ) ;
insert into PLACE values ( 680 , 'B' ) ;
insert into PLACE values ( 681 , 'B' ) ;
insert into PLACE values ( 682 , 'B' ) ;
insert into PLACE values ( 683 , 'B' ) ;
insert into PLACE values ( 684 , 'B' ) ;
insert into PLACE values ( 685 , 'B' ) ;
insert into PLACE values ( 686 , 'B' ) ;
insert into PLACE values ( 687 , 'B' ) ;
insert into PLACE values ( 688 , 'B' ) ;
insert into PLACE values ( 689 , 'B' ) ;
insert into PLACE values ( 690 , 'B' ) ;
insert into PLACE values ( 691 , 'B' ) ;
insert into PLACE values ( 692 , 'B' ) ;
insert into PLACE values ( 693 , 'B' ) ;
insert into PLACE values ( 694 , 'B' ) ;
insert into PLACE values ( 695 , 'B' ) ;
insert into PLACE values ( 696 , 'B' ) ;
insert into PLACE values ( 697 , 'B' ) ;
insert into PLACE values ( 698 , 'B' ) ;
insert into PLACE values ( 699 , 'B' ) ;
insert into PLACE values ( 700 , 'B' ) ;
insert into PLACE values ( 701 , 'B' ) ;
insert into PLACE values ( 702 , 'B' ) ;
insert into PLACE values ( 703 , 'B' ) ;
insert into PLACE values ( 704 , 'B' ) ;
insert into PLACE values ( 705 , 'B' ) ;
insert into PLACE values ( 706 , 'B' ) ;
insert into PLACE values ( 707 , 'B' ) ;
insert into PLACE values ( 708 , 'B' ) ;
insert into PLACE values ( 709 , 'B' ) ;
insert into PLACE values ( 710 , 'B' ) ;
insert into PLACE values ( 711 , 'B' ) ;
insert into PLACE values ( 712 , 'B' ) ;
insert into PLACE values ( 713 , 'B' ) ;
insert into PLACE values ( 714 , 'B' ) ;
insert into PLACE values ( 715 , 'B' ) ;
insert into PLACE values ( 716 , 'B' ) ;
insert into PLACE values ( 717 , 'B' ) ;
insert into PLACE values ( 718 , 'B' ) ;
insert into PLACE values ( 719 , 'B' ) ;
insert into PLACE values ( 720 , 'B' ) ;
insert into PLACE values ( 721 , 'B' ) ;
insert into PLACE values ( 722 , 'B' ) ;
insert into PLACE values ( 723 , 'B' ) ;
insert into PLACE values ( 724 , 'B' ) ;
insert into PLACE values ( 725 , 'B' ) ;
insert into PLACE values ( 726 , 'B' ) ;
insert into PLACE values ( 727 , 'B' ) ;
insert into PLACE values ( 728 , 'B' ) ;
insert into PLACE values ( 729 , 'B' ) ;
insert into PLACE values ( 730 , 'B' ) ;
insert into PLACE values ( 731 , 'B' ) ;
insert into PLACE values ( 732 , 'B' ) ;
insert into PLACE values ( 733 , 'B' ) ;
insert into PLACE values ( 734 , 'B' ) ;
insert into PLACE values ( 735 , 'B' ) ;
insert into PLACE values ( 736 , 'B' ) ;
insert into PLACE values ( 737 , 'B' ) ;
insert into PLACE values ( 738 , 'B' ) ;
insert into PLACE values ( 739 , 'B' ) ;
insert into PLACE values ( 740 , 'B' ) ;
insert into PLACE values ( 741 , 'B' ) ;
insert into PLACE values ( 742 , 'B' ) ;
insert into PLACE values ( 743 , 'B' ) ;
insert into PLACE values ( 744 , 'B' ) ;
insert into PLACE values ( 745 , 'B' ) ;
insert into PLACE values ( 746 , 'B' ) ;
insert into PLACE values ( 747 , 'B' ) ;
insert into PLACE values ( 748 , 'B' ) ;
insert into PLACE values ( 749 , 'B' ) ;
insert into PLACE values ( 750 , 'B' ) ;
insert into PLACE values ( 751 , 'B' ) ;
insert into PLACE values ( 752 , 'B' ) ;
insert into PLACE values ( 753 , 'B' ) ;
insert into PLACE values ( 754 , 'B' ) ;
insert into PLACE values ( 755 , 'B' ) ;
insert into PLACE values ( 756 , 'B' ) ;
insert into PLACE values ( 757 , 'B' ) ;
insert into PLACE values ( 758 , 'B' ) ;
insert into PLACE values ( 759 , 'B' ) ;
insert into PLACE values ( 760 , 'B' ) ;
insert into PLACE values ( 761 , 'B' ) ;
insert into PLACE values ( 762 , 'B' ) ;
insert into PLACE values ( 763 , 'B' ) ;
insert into PLACE values ( 764 , 'B' ) ;
insert into PLACE values ( 765 , 'B' ) ;
insert into PLACE values ( 766 , 'B' ) ;
insert into PLACE values ( 767 , 'B' ) ;
insert into PLACE values ( 768 , 'B' ) ;
insert into PLACE values ( 769 , 'B' ) ;
insert into PLACE values ( 770 , 'B' ) ;
insert into PLACE values ( 771 , 'B' ) ;
insert into PLACE values ( 772 , 'B' ) ;
insert into PLACE values ( 773 , 'B' ) ;
insert into PLACE values ( 774 , 'B' ) ;
insert into PLACE values ( 775 , 'B' ) ;
insert into PLACE values ( 776 , 'B' ) ;
insert into PLACE values ( 777 , 'B' ) ;
insert into PLACE values ( 778 , 'B' ) ;
insert into PLACE values ( 779 , 'B' ) ;
insert into PLACE values ( 780 , 'B' ) ;
insert into PLACE values ( 781 , 'B' ) ;
insert into PLACE values ( 782 , 'B' ) ;
insert into PLACE values ( 783 , 'B' ) ;
insert into PLACE values ( 784 , 'B' ) ;
insert into PLACE values ( 785 , 'B' ) ;
insert into PLACE values ( 786 , 'B' ) ;
insert into PLACE values ( 787 , 'B' ) ;
insert into PLACE values ( 788 , 'B' ) ;
insert into PLACE values ( 789 , 'B' ) ;
insert into PLACE values ( 790 , 'B' ) ;
insert into PLACE values ( 791 , 'B' ) ;
insert into PLACE values ( 792 , 'B' ) ;
insert into PLACE values ( 793 , 'B' ) ;
insert into PLACE values ( 794 , 'B' ) ;
insert into PLACE values ( 795 , 'B' ) ;
insert into PLACE values ( 796 , 'B' ) ;
insert into PLACE values ( 797 , 'B' ) ;
insert into PLACE values ( 798 , 'B' ) ;
insert into PLACE values ( 799 , 'B' ) ;
insert into PLACE values ( 800 , 'B' ) ;
insert into PLACE values ( 801 , 'B' ) ;
insert into PLACE values ( 802 , 'B' ) ;
insert into PLACE values ( 803 , 'B' ) ;
insert into PLACE values ( 804 , 'B' ) ;
insert into PLACE values ( 805 , 'B' ) ;
insert into PLACE values ( 806 , 'B' ) ;
insert into PLACE values ( 807 , 'B' ) ;
insert into PLACE values ( 808 , 'B' ) ;
insert into PLACE values ( 809 , 'B' ) ;
insert into PLACE values ( 810 , 'B' ) ;
insert into PLACE values ( 811 , 'B' ) ;
insert into PLACE values ( 812 , 'B' ) ;
insert into PLACE values ( 813 , 'B' ) ;
insert into PLACE values ( 814 , 'B' ) ;
insert into PLACE values ( 815 , 'B' ) ;
insert into PLACE values ( 816 , 'B' ) ;
insert into PLACE values ( 817 , 'B' ) ;
insert into PLACE values ( 818 , 'B' ) ;
insert into PLACE values ( 819 , 'B' ) ;
insert into PLACE values ( 820 , 'B' ) ;
insert into PLACE values ( 821 , 'B' ) ;
insert into PLACE values ( 822 , 'B' ) ;
insert into PLACE values ( 823 , 'B' ) ;
insert into PLACE values ( 824 , 'B' ) ;
insert into PLACE values ( 825 , 'B' ) ;
insert into PLACE values ( 826 , 'B' ) ;
insert into PLACE values ( 827 , 'B' ) ;
insert into PLACE values ( 828 , 'B' ) ;
insert into PLACE values ( 829 , 'B' ) ;
insert into PLACE values ( 830 , 'B' ) ;
insert into PLACE values ( 831 , 'B' ) ;
insert into PLACE values ( 832 , 'B' ) ;
insert into PLACE values ( 833 , 'B' ) ;
insert into PLACE values ( 834 , 'B' ) ;
insert into PLACE values ( 835 , 'B' ) ;
insert into PLACE values ( 836 , 'B' ) ;
insert into PLACE values ( 837 , 'B' ) ;
insert into PLACE values ( 838 , 'B' ) ;
insert into PLACE values ( 839 , 'B' ) ;
insert into PLACE values ( 840 , 'B' ) ;
insert into PLACE values ( 841 , 'B' ) ;
insert into PLACE values ( 842 , 'B' ) ;
insert into PLACE values ( 843 , 'B' ) ;
insert into PLACE values ( 844 , 'B' ) ;
insert into PLACE values ( 845 , 'B' ) ;
insert into PLACE values ( 846 , 'B' ) ;
insert into PLACE values ( 847 , 'B' ) ;
insert into PLACE values ( 848 , 'B' ) ;
insert into PLACE values ( 849 , 'B' ) ;
insert into PLACE values ( 850 , 'B' ) ;
insert into PLACE values ( 851 , 'B' ) ;
insert into PLACE values ( 852 , 'B' ) ;
insert into PLACE values ( 853 , 'B' ) ;
insert into PLACE values ( 854 , 'B' ) ;
insert into PLACE values ( 855 , 'B' ) ;
insert into PLACE values ( 856 , 'B' ) ;
insert into PLACE values ( 857 , 'B' ) ;
insert into PLACE values ( 858 , 'B' ) ;
insert into PLACE values ( 859 , 'B' ) ;
insert into PLACE values ( 860 , 'B' ) ;
insert into PLACE values ( 861 , 'B' ) ;
insert into PLACE values ( 862 , 'B' ) ;
insert into PLACE values ( 863 , 'B' ) ;
insert into PLACE values ( 864 , 'B' ) ;
insert into PLACE values ( 865 , 'B' ) ;
insert into PLACE values ( 866 , 'B' ) ;
insert into PLACE values ( 867 , 'B' ) ;
insert into PLACE values ( 868 , 'B' ) ;
insert into PLACE values ( 869 , 'B' ) ;
insert into PLACE values ( 870 , 'B' ) ;
insert into PLACE values ( 871 , 'B' ) ;
insert into PLACE values ( 872 , 'B' ) ;
insert into PLACE values ( 873 , 'B' ) ;
insert into PLACE values ( 874 , 'B' ) ;
insert into PLACE values ( 875 , 'B' ) ;
insert into PLACE values ( 876 , 'B' ) ;
insert into PLACE values ( 877 , 'B' ) ;
insert into PLACE values ( 878 , 'B' ) ;
insert into PLACE values ( 879 , 'B' ) ;
insert into PLACE values ( 880 , 'B' ) ;
insert into PLACE values ( 881 , 'B' ) ;
insert into PLACE values ( 882 , 'B' ) ;
insert into PLACE values ( 883 , 'B' ) ;
insert into PLACE values ( 884 , 'B' ) ;
insert into PLACE values ( 885 , 'B' ) ;
insert into PLACE values ( 886 , 'B' ) ;
insert into PLACE values ( 887 , 'B' ) ;
insert into PLACE values ( 888 , 'B' ) ;
insert into PLACE values ( 889 , 'B' ) ;
insert into PLACE values ( 890 , 'B' ) ;
insert into PLACE values ( 891 , 'B' ) ;
insert into PLACE values ( 892 , 'B' ) ;
insert into PLACE values ( 893 , 'B' ) ;
insert into PLACE values ( 894 , 'B' ) ;
insert into PLACE values ( 895 , 'B' ) ;
insert into PLACE values ( 896 , 'B' ) ;
insert into PLACE values ( 897 , 'B' ) ;
insert into PLACE values ( 898 , 'B' ) ;
insert into PLACE values ( 899 , 'B' ) ;
insert into PLACE values ( 900 , 'B' ) ;
insert into PLACE values ( 901 , 'B' ) ;
insert into PLACE values ( 902 , 'B' ) ;
insert into PLACE values ( 903 , 'B' ) ;
insert into PLACE values ( 904 , 'B' ) ;
insert into PLACE values ( 905 , 'B' ) ;
insert into PLACE values ( 906 , 'B' ) ;
insert into PLACE values ( 907 , 'B' ) ;
insert into PLACE values ( 908 , 'B' ) ;
insert into PLACE values ( 909 , 'B' ) ;
insert into PLACE values ( 910 , 'B' ) ;
insert into PLACE values ( 911 , 'B' ) ;
insert into PLACE values ( 912 , 'B' ) ;
insert into PLACE values ( 913 , 'B' ) ;
insert into PLACE values ( 914 , 'B' ) ;
insert into PLACE values ( 915 , 'B' ) ;
insert into PLACE values ( 916 , 'B' ) ;
insert into PLACE values ( 917 , 'B' ) ;
insert into PLACE values ( 918 , 'B' ) ;
insert into PLACE values ( 919 , 'B' ) ;
insert into PLACE values ( 920 , 'B' ) ;
insert into PLACE values ( 921 , 'B' ) ;
insert into PLACE values ( 922 , 'B' ) ;
insert into PLACE values ( 923 , 'B' ) ;
insert into PLACE values ( 924 , 'B' ) ;
insert into PLACE values ( 925 , 'B' ) ;
insert into PLACE values ( 926 , 'B' ) ;
insert into PLACE values ( 927 , 'B' ) ;
insert into PLACE values ( 928 , 'B' ) ;
insert into PLACE values ( 929 , 'B' ) ;
insert into PLACE values ( 930 , 'B' ) ;
insert into PLACE values ( 931 , 'B' ) ;
insert into PLACE values ( 932 , 'B' ) ;
insert into PLACE values ( 933 , 'B' ) ;
insert into PLACE values ( 934 , 'B' ) ;
insert into PLACE values ( 935 , 'B' ) ;
insert into PLACE values ( 936 , 'B' ) ;
insert into PLACE values ( 937 , 'B' ) ;
insert into PLACE values ( 938 , 'B' ) ;
insert into PLACE values ( 939 , 'B' ) ;
insert into PLACE values ( 940 , 'B' ) ;
insert into PLACE values ( 941 , 'B' ) ;
insert into PLACE values ( 942 , 'B' ) ;
insert into PLACE values ( 943 , 'B' ) ;
insert into PLACE values ( 944 , 'B' ) ;
insert into PLACE values ( 945 , 'B' ) ;
insert into PLACE values ( 946 , 'B' ) ;
insert into PLACE values ( 947 , 'B' ) ;
insert into PLACE values ( 948 , 'B' ) ;
insert into PLACE values ( 949 , 'B' ) ;
insert into PLACE values ( 950 , 'B' ) ;
insert into PLACE values ( 951 , 'B' ) ;
insert into PLACE values ( 952 , 'B' ) ;
insert into PLACE values ( 953 , 'B' ) ;
insert into PLACE values ( 954 , 'B' ) ;
insert into PLACE values ( 955 , 'B' ) ;
insert into PLACE values ( 956 , 'B' ) ;
insert into PLACE values ( 957 , 'B' ) ;
insert into PLACE values ( 958 , 'B' ) ;
insert into PLACE values ( 959 , 'B' ) ;
insert into PLACE values ( 960 , 'B' ) ;
insert into PLACE values ( 961 , 'B' ) ;
insert into PLACE values ( 962 , 'B' ) ;
insert into PLACE values ( 963 , 'B' ) ;
insert into PLACE values ( 964 , 'B' ) ;
insert into PLACE values ( 965 , 'B' ) ;
insert into PLACE values ( 966 , 'B' ) ;
insert into PLACE values ( 967 , 'B' ) ;
insert into PLACE values ( 968 , 'B' ) ;
insert into PLACE values ( 969 , 'B' ) ;
insert into PLACE values ( 970 , 'B' ) ;
insert into PLACE values ( 971 , 'B' ) ;
insert into PLACE values ( 972 , 'B' ) ;
insert into PLACE values ( 973 , 'B' ) ;
insert into PLACE values ( 974 , 'B' ) ;
insert into PLACE values ( 975 , 'B' ) ;
insert into PLACE values ( 976 , 'B' ) ;
insert into PLACE values ( 977 , 'B' ) ;
insert into PLACE values ( 978 , 'B' ) ;
insert into PLACE values ( 979 , 'B' ) ;
insert into PLACE values ( 980 , 'B' ) ;
insert into PLACE values ( 981 , 'B' ) ;
insert into PLACE values ( 982 , 'B' ) ;
insert into PLACE values ( 983 , 'B' ) ;
insert into PLACE values ( 984 , 'B' ) ;
insert into PLACE values ( 985 , 'B' ) ;
insert into PLACE values ( 986 , 'B' ) ;
insert into PLACE values ( 987 , 'B' ) ;
insert into PLACE values ( 988 , 'B' ) ;
insert into PLACE values ( 989 , 'B' ) ;
insert into PLACE values ( 990 , 'B' ) ;
insert into PLACE values ( 991 , 'B' ) ;
insert into PLACE values ( 992 , 'B' ) ;
insert into PLACE values ( 993 , 'B' ) ;
insert into PLACE values ( 994 , 'B' ) ;
insert into PLACE values ( 995 , 'B' ) ;
insert into PLACE values ( 996 , 'B' ) ;
insert into PLACE values ( 997 , 'B' ) ;
insert into PLACE values ( 998 , 'B' ) ;
insert into PLACE values ( 999 , 'B' ) ;

commit ;

-- SEANCE

insert into SEANCE values (  1 ,  2 , 'B' , '23-MAY-96' , 14 ) ;
insert into SEANCE values (  2 , 18 , 'A' , '23-MAY-96' , 14 ) ;
insert into SEANCE values (  3 , 20 , 'C' , '23-MAY-96' , 14 ) ;
insert into SEANCE values (  4 ,  7 , 'B' , '23-MAY-96' , 16 ) ;
insert into SEANCE values (  5 , 14 , 'B' , '23-MAY-96' , 16 ) ;
insert into SEANCE values (  6 ,  7 , 'B' , '23-MAY-96' , 18 ) ;
insert into SEANCE values (  7 , 14 , 'B' , '23-MAY-96' , 18 ) ;
insert into SEANCE values (  8 ,  2 , 'B' , '23-MAY-96' , 20 ) ;
insert into SEANCE values (  9 , 19 , 'A' , '23-MAY-96' , 20 ) ;
insert into SEANCE values ( 10 , 20 , 'C' , '23-MAY-96' , 20 ) ;
insert into SEANCE values ( 11 ,  7 , 'B' , '23-MAY-96' , 22 ) ;
insert into SEANCE values ( 12 , 14 , 'B' , '23-MAY-96' , 22 ) ;
insert into SEANCE values ( 13 ,  7 , 'B' , '24-MAY-96' , 14 ) ;
insert into SEANCE values ( 14 , 14 , 'B' , '24-MAY-96' , 14 ) ;
insert into SEANCE values ( 15 , 19 , 'A' , '24-MAY-96' , 14 ) ;
insert into SEANCE values ( 16 ,  2 , 'B' , '24-MAY-96' , 16 ) ;
insert into SEANCE values ( 17 , 20 , 'C' , '24-MAY-96' , 16 ) ;
insert into SEANCE values ( 18 ,  2 , 'B' , '24-MAY-96' , 18 ) ;
insert into SEANCE values ( 19 , 20 , 'C' , '24-MAY-96' , 18 ) ;
insert into SEANCE values ( 20 ,  7 , 'B' , '24-MAY-96' , 20 ) ;
insert into SEANCE values ( 21 , 14 , 'B' , '24-MAY-96' , 20 ) ;
insert into SEANCE values ( 22 , 18 , 'A' , '24-MAY-96' , 20 ) ;
insert into SEANCE values ( 23 ,  2 , 'B' , '24-MAY-96' , 22 ) ;
insert into SEANCE values ( 24 , 20 , 'C' , '24-MAY-96' , 22 ) ;

commit ;

-- RESERVATION

insert into RESERVATION values (  1 ,    8 , 'LAURENCE' ) ;
insert into RESERVATION values (  1 ,   64 , 'DENIS' ) ;
insert into RESERVATION values (  1 ,  128 , 'DAVID' ) ;
insert into RESERVATION values (  2 ,   16 , 'SERGE' ) ;
insert into RESERVATION values (  2 ,   32 , 'CHRISTOPHE' ) ;
insert into RESERVATION values (  2 ,   33 , 'DANIELLE' ) ;
insert into RESERVATION values (  2 ,   64 , 'LUC' ) ;
insert into RESERVATION values (  2 ,  128 , 'NICOLAS' ) ;
insert into RESERVATION values (  2 ,  256 , 'PATRICK' ) ;
insert into RESERVATION values (  2 ,  512 , 'FLORENT' ) ;
insert into RESERVATION values (  5 ,   32 , 'CLAUDE' ) ;
insert into RESERVATION values (  5 ,   64 , 'DELPHINE' ) ;
insert into RESERVATION values (  8 ,  256 , 'CYRIL' ) ;
insert into RESERVATION values ( 10 ,    2 , 'SUZANNE' ) ;
insert into RESERVATION values ( 10 ,    4 , 'OLIVIER' ) ;
insert into RESERVATION values ( 10 ,    8 , 'MATTHIEU' ) ;
insert into RESERVATION values ( 10 ,   16 , 'PIERRE' ) ;
insert into RESERVATION values ( 10 ,   32 , 'SEBASTIEN' ) ;
insert into RESERVATION values ( 10 ,   64 , 'ERIC' ) ;
insert into RESERVATION values ( 10 ,  128 , 'BENOIT' ) ;
insert into RESERVATION values ( 10 ,  129 , 'CELINE' ) ;
insert into RESERVATION values ( 10 ,  256 , 'YOHANN' ) ;
insert into RESERVATION values ( 10 ,  512 , 'GUILLAUME' ) ;
insert into RESERVATION values ( 10 ,  513 , 'MICHELLE' ) ;
insert into RESERVATION values ( 12 ,    8 , 'THIBAUT' ) ;
insert into RESERVATION values ( 12 ,   32 , 'FRANCOISE' ) ;
insert into RESERVATION values ( 12 ,   64 , 'XAVIER' ) ;
insert into RESERVATION values ( 12 ,  128 , 'SAMUEL' ) ;
insert into RESERVATION values ( 15 ,    8 , 'JEAN' ) ;
insert into RESERVATION values ( 15 ,   16 , 'SANDRINE' ) ;
insert into RESERVATION values ( 15 ,   17 , 'VLADIMIR' ) ;
insert into RESERVATION values ( 15 ,  128 , 'FRANCK' ) ;
insert into RESERVATION values ( 15 ,  256 , 'JEROME' ) ;
insert into RESERVATION values ( 16 ,  128 , 'ISABELLE' ) ;
insert into RESERVATION values ( 16 ,  512 , 'ALAIN' ) ;
insert into RESERVATION values ( 17 ,   16 , 'STEPHANE' ) ;
insert into RESERVATION values ( 17 ,   32 , 'HUGUES' ) ;
insert into RESERVATION values ( 17 ,   64 , 'VINCENT' ) ;
insert into RESERVATION values ( 20 ,   16 , 'THEODORE' ) ;
insert into RESERVATION values ( 20 ,   64 , 'GREGORY' ) ;
insert into RESERVATION values ( 20 ,  128 , 'ROLANDE' ) ;
insert into RESERVATION values ( 20 ,  256 , 'PHILIPPE' ) ;

commit ;

-- ============================================================
--    verification des donnees
-- ============================================================

select count(*),'= 35 ?','ACTEUR' from ACTEUR 
union
select count(*),'= 21 ?','FILM' from FILM 
union
select count(*),'= 15 ?','REALISATEUR' from REALISATEUR 
union
select count(*),'= 40 ?','ROLE' from ROLE 
union
select count(*),'= 3 ?','CATEGORIE_PLACE' from CATEGORIE_PLACE 
union
select count(*),'= 3 ?','CATEGORIE_SEANCE' from CATEGORIE_SEANCE 
union
select count(*),'= 6 ?','TARIF' from TARIF 
union
select count(*),'= 1000 ?','PLACE' from PLACE 
union
select count(*), '= 24 ?','SEANCE' from SEANCE 
union
select count(*), '= 42 ?','RESERVATION' from RESERVATION ;
